name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: Pypi-upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Build artifacts
        run: python3.12 -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
